import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Plus, Users, Lock, Unlock, LogOut, RefreshCw, Key, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogClose } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { Room } from '@/types/game';

// Type for the verify_and_join_room RPC response
interface JoinRoomResponse {
  success: boolean;
  error?: string;
  message?: string;
}

// Type for the rooms_public view (excludes password)
interface RoomPublicRow {
  id: string;
  code: string;
  name: string;
  host_id: string;
  is_private: boolean | null;
  max_players: number | null;
  status: string | null;
  created_at: string | null;
  current_turn: string | null;
  turn_started_at: string | null;
  dutch_caller: string | null;
  room_players?: { count: number }[];
}

const Lobby = () => {
  const navigate = useNavigate();
  const { user, signOut } = useAuth();
  const { toast } = useToast();
  const [rooms, setRooms] = useState<Room[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [joinCode, setJoinCode] = useState('');
  const [joining, setJoining] = useState(false);
  
  // Create room form
  const [roomName, setRoomName] = useState('');
  const [isPrivate, setIsPrivate] = useState(false);
  const [password, setPassword] = useState('');
  const [maxPlayers, setMaxPlayers] = useState('4');

  // Password dialog state for joining private rooms
  const [passwordDialogOpen, setPasswordDialogOpen] = useState(false);
  const [pendingRoomId, setPendingRoomId] = useState<string | null>(null);
  const [pendingRoomIsPrivate, setPendingRoomIsPrivate] = useState(false);
  const [joinPassword, setJoinPassword] = useState('');

  useEffect(() => {
    if (!user) {
      navigate('/');
      return;
    }
    fetchRooms();
    
    // Subscribe to room changes
    const channel = supabase
      .channel('rooms-changes')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'rooms' }, () => {
        fetchRooms();
      })
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [user, navigate]);

  const fetchRooms = async () => {
    // Use rooms_public view to avoid exposing passwords
    const { data, error } = await supabase
      .from('rooms_public' as any)
      .select(`
        *,
        room_players(count)
      `)
      .eq('is_private', false)
      .in('status', ['waiting'])
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching rooms:', error);
    } else {
      const rooms = (data as unknown as RoomPublicRow[]) || [];
      setRooms(rooms.map(r => ({
        id: r.id,
        code: r.code,
        name: r.name,
        hostId: r.host_id,
        isPrivate: r.is_private,
        maxPlayers: r.max_players,
        status: r.status as Room['status'],
        createdAt: new Date(r.created_at || ''),
        players: [],
      })));
    }
    setLoading(false);
  };

  const createRoom = async () => {
    const trimmedName = roomName.trim();
    
    // Client-side validation with feedback
    if (!user || !trimmedName) return;
    
    if (trimmedName.length > 100) {
      toast({ 
        variant: 'destructive', 
        title: 'Nome inválido', 
        description: 'O nome da sala deve ter no máximo 100 caracteres' 
      });
      return;
    }
    
    setCreating(true);
    
    // Room code is now auto-generated by the database using generate_room_code()
    const { data, error } = await supabase
      .from('rooms')
      .insert({
        // 'code' field removed - database auto-generates using secure server-side function
        name: trimmedName,
        host_id: user.id,
        is_private: isPrivate,
        password: isPrivate ? password : null,
        max_players: parseInt(maxPlayers),
      })
      .select()
      .single();

    if (error) {
      toast({ variant: 'destructive', title: 'Erro', description: 'Não foi possível criar a sala.' });
    } else if (data) {
      // Join the room as host using the secure RPC
      const { data: joinData, error: joinError } = await supabase.rpc('verify_and_join_room', {
        p_room_id: data.id,
        p_player_id: user.id,
        p_password: isPrivate ? password : '',
        p_position: 0,
      });

      const joinResponse = joinData as unknown as JoinRoomResponse;
      if (joinError || (joinResponse && !joinResponse.success)) {
        toast({ variant: 'destructive', title: 'Erro', description: 'Não foi possível entrar na sala.' });
      } else {
        navigate(`/room/${data.id}`);
      }
    }
    setCreating(false);
  };

  const joinRoom = async (roomId: string, roomPassword: string = '') => {
    if (!user) return;
    
    setJoining(true);
    
    // Get current player count for position
    const { data: players } = await supabase
      .from('room_players')
      .select('position')
      .eq('room_id', roomId)
      .order('position', { ascending: false });

    const nextPosition = (players?.[0]?.position ?? -1) + 1;
    
    // Use the secure RPC function that validates password server-side
    const { data, error } = await supabase.rpc('verify_and_join_room', {
      p_room_id: roomId,
      p_player_id: user.id,
      p_password: roomPassword,
      p_position: nextPosition,
    });

    setJoining(false);

    if (error) {
      toast({ variant: 'destructive', title: 'Erro', description: 'Não foi possível entrar na sala.' });
      return;
    }

    // Handle RPC response - cast to proper type
    const response = data as unknown as JoinRoomResponse;
    if (response && typeof response === 'object') {
      if (response.success) {
        setPasswordDialogOpen(false);
        setJoinPassword('');
        setPendingRoomId(null);
        navigate(`/room/${roomId}`);
      } else if (response.error) {
        const errorMessage = response.error === 'Invalid password' 
          ? 'Senha incorreta' 
          : response.error === 'Room is full'
          ? 'Sala cheia'
          : response.error === 'Room is not accepting players'
          ? 'A sala não está aceitando jogadores'
          : 'Não foi possível entrar na sala.';
        toast({ variant: 'destructive', title: 'Erro', description: errorMessage });
      }
    }
  };

  const handleJoinClick = async (roomId: string, isRoomPrivate: boolean) => {
    if (isRoomPrivate) {
      // Show password dialog for private rooms
      setPendingRoomId(roomId);
      setPendingRoomIsPrivate(true);
      setJoinPassword('');
      setPasswordDialogOpen(true);
    } else {
      // Join public room directly
      await joinRoom(roomId, '');
    }
  };

  const handlePasswordSubmit = async () => {
    if (!pendingRoomId) return;
    await joinRoom(pendingRoomId, joinPassword);
  };


  const joinByCode = async () => {
    if (!joinCode.trim()) return;
    
    // Use rooms_public view to avoid exposing passwords
    const { data, error } = await supabase
      .from('rooms_public' as any)
      .select('id, is_private')
      .eq('code', joinCode.toUpperCase())
      .maybeSingle();

    if (error || !data) {
      toast({ variant: 'destructive', title: 'Sala não encontrada', description: 'Verifique o código.' });
    } else {
      const roomData = data as unknown as { id: string; is_private: boolean | null };
      // Check if private room needs password
      if (roomData.is_private) {
        setPendingRoomId(roomData.id);
        setPendingRoomIsPrivate(true);
        setJoinPassword('');
        setPasswordDialogOpen(true);
      } else {
        await joinRoom(roomData.id, '');
      }
    }
  };

  const handleSignOut = async () => {
    await signOut();
    navigate('/');
  };

  if (!user) return null;

  return (
    <div className="min-h-screen p-4 relative overflow-hidden">
      <div className="absolute inset-0 bg-game-table opacity-30" />
      
      <div className="relative z-10 max-w-4xl mx-auto">
        {/* Header */}
        <motion.div
          className="flex items-center justify-between mb-8"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <h1 className="text-3xl font-bold text-gradient-primary">Lobby</h1>
          <Button variant="outline" size="sm" onClick={handleSignOut}>
            <LogOut className="w-4 h-4 mr-2" />
            Sair
          </Button>
        </motion.div>

        {/* Actions */}
        <motion.div
          className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
        >
          {/* Create Room */}
          <Dialog>
            <DialogTrigger asChild>
              <Button className="h-20 text-lg gap-3">
                <Plus className="w-6 h-6" />
                Criar Sala
              </Button>
            </DialogTrigger>
            <DialogContent className="glass-card border-white/10">
              <DialogHeader>
                <DialogTitle>Criar Nova Sala</DialogTitle>
              </DialogHeader>
              <div className="space-y-4 mt-4">
                <div className="space-y-2">
                  <Label>Nome da Sala</Label>
                  <Input
                    value={roomName}
                    onChange={(e) => setRoomName(e.target.value)}
                    placeholder="Minha sala"
                    className="glass-input"
                  />
                </div>
                <div className="space-y-2">
                  <Label>Máximo de Jogadores</Label>
                  <Select value={maxPlayers} onValueChange={setMaxPlayers}>
                    <SelectTrigger className="glass-input">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {[2, 3, 4, 5, 6].map(n => (
                        <SelectItem key={n} value={n.toString()}>{n} jogadores</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex items-center justify-between">
                  <Label>Sala Privada</Label>
                  <Switch checked={isPrivate} onCheckedChange={setIsPrivate} />
                </div>
                {isPrivate && (
                  <div className="space-y-2">
                    <Label>Senha</Label>
                    <Input
                      type="password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      placeholder="••••••"
                      className="glass-input"
                    />
                  </div>
                )}
                <Button onClick={createRoom} disabled={creating || !roomName.trim()} className="w-full">
                  {creating ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Plus className="w-4 h-4 mr-2" />}
                  Criar
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          {/* Join by Code */}
          <div className="glass-card rounded-xl p-4 flex gap-2">
            <Input
              value={joinCode}
              onChange={(e) => setJoinCode(e.target.value.toUpperCase())}
              placeholder="Código da sala"
              maxLength={6}
              className="glass-input uppercase"
            />
            <Button onClick={joinByCode} disabled={!joinCode.trim() || joining}>
              {joining ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Key className="w-4 h-4 mr-2" />}
              Entrar
            </Button>
          </div>
        </motion.div>

        {/* Room List */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
        >
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold flex items-center gap-2">
              <Users className="w-5 h-5" />
              Salas Públicas
            </h2>
            <Button variant="ghost" size="sm" onClick={fetchRooms}>
              <RefreshCw className="w-4 h-4" />
            </Button>
          </div>

          {loading ? (
            <div className="text-center py-8">
              <Loader2 className="w-8 h-8 animate-spin mx-auto text-primary" />
            </div>
          ) : rooms.length === 0 ? (
            <div className="text-center py-8 glass-card rounded-xl">
              <p className="text-muted-foreground">Nenhuma sala disponível</p>
              <p className="text-sm text-muted-foreground">Crie uma nova sala para começar!</p>
            </div>
          ) : (
            <div className="grid gap-3">
              {rooms.map((room) => (
                <motion.div
                  key={room.id}
                  className="glass-card rounded-xl p-4 flex items-center justify-between"
                  whileHover={{ scale: 1.01 }}
                >
                  <div className="flex items-center gap-3">
                    {room.isPrivate ? (
                      <Lock className="w-5 h-5 text-accent" />
                    ) : (
                      <Unlock className="w-5 h-5 text-primary" />
                    )}
                    <div>
                      <h3 className="font-medium">{room.name}</h3>
                      <p className="text-xs text-muted-foreground">
                        Código: {room.code} • Máx: {room.maxPlayers}
                      </p>
                    </div>
                  </div>
                  <Button size="sm" onClick={() => handleJoinClick(room.id, room.isPrivate ?? false)} disabled={joining}>
                    Entrar
                  </Button>
                </motion.div>
              ))}
            </div>
          )}
        </motion.div>

        {/* Password Dialog for Private Rooms */}
        <Dialog open={passwordDialogOpen} onOpenChange={setPasswordDialogOpen}>
          <DialogContent className="glass-card border-white/10">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Lock className="w-5 h-5" />
                Sala Privada
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4 mt-4">
              <p className="text-sm text-muted-foreground">
                Esta sala requer uma senha para entrar.
              </p>
              <div className="space-y-2">
                <Label>Senha</Label>
                <Input
                  type="password"
                  value={joinPassword}
                  onChange={(e) => setJoinPassword(e.target.value)}
                  placeholder="Digite a senha"
                  className="glass-input"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      handlePasswordSubmit();
                    }
                  }}
                />
              </div>
              <div className="flex gap-2">
                <DialogClose asChild>
                  <Button variant="outline" className="flex-1">
                    Cancelar
                  </Button>
                </DialogClose>
                <Button 
                  onClick={handlePasswordSubmit} 
                  disabled={joining || !joinPassword.trim()} 
                  className="flex-1"
                >
                  {joining ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Key className="w-4 h-4 mr-2" />}
                  Entrar
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
};

export default Lobby;
